version: '3.8'

services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./data/:/var/lib/mysql
      - ./initdb/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    networks:
      - aviationhub

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DESIGN=dracula
      - ADMINER_DEFAULT_SERVER=database
    ports:
      - 8080:8080
    depends_on: 
      - database
    networks: 
      - aviationhub

networks:
  aviationhub: